### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Kawa-oneechan** [Kawa-oneechan/dumblr#1]
In no particular order:
- [ ] Reblogging
- [ ] Registering
  - [ ] Sub-blogs
- [ ] Profile editing
  - [ ] Uploading avatars
- [ ] Post editing
- [ ] Preview while compositing
- [ ] Fancy tag field
- [ ] Following
- [x] Text posts
- [ ] Photo posts
- [ ] Ask posts
- [ ] Link posts
- [ ] Quote posts
- [ ] Notification badge
- [ ] Customizing
  - [ ] Fully custom templates on individual blogs
- [ ] Reporting
  - [ ] Auto-Reporter™

Look into alternative...
- [ ] Databases
- [ ] Template engines
